# Generated by Django 2.2.4 on 2019-09-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oritest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='question_text',
            new_name='questionnaire_text',
        ),
    ]
