# Generated by Django 2.2.4 on 2019-09-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oritest', '0002_auto_20190912_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='C1',
        ),
        migrations.AddField(
            model_name='choice',
            name='C2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='C3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='C4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='D1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='D2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='D3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='D4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='D5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='D6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='E1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='E2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='N1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='N2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='N3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='N4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='S1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='S2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='S3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='S4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='S5',
            field=models.IntegerField(default=0),
        ),
    ]
